dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8', 'x1e9']
  output_label: 'x1e9'
  test_path: 'data/test/3D/homo/64x64x64'

model:
  architecture: 'ResidualDnCNN'
  checkpoint: "checkpoints/3D/blind-denoising/resmcnet/version_2/checkpoints/epoch=1499-MSE=0.0036-SSIM=0.9742-PSNR=63.0294.ckpt"
  ResidualDnCNN:
    do_3d: True
output_dir: 'results/3D/resmcnet/homo/64x64x64/'