pytorch_lightning:
  checkpoint_dir: './checkpoints/3D/loss-function'
  experiment_name: 'mse+ssim'
  num_gpus: 8
  num_nodes: 1
  accelerator: 'ddp'
  visualize: False
  seed: 1

dataset:
  input_labels: ['x1e5']
  valid_labels: ['x1e5']
  output_label: 'x1e9'
  train_path: 'data/train/3D/64x64x64'
  valid_path: 'data/test/3D/refractive-64x64x64'

model:
  architecture: 'Cascaded'
  Cascaded:
    do_3d: True
    num_dncnn: 1
    num_dncnn_layers: 17
loss:
  loss_option: ['MSE', 'SSIM']
  loss_weight: [1, -1]

solver:
  optimizer: 'AdamW'
  batch_size: 4
  base_lr: 1e-4
  total_iterations: 500
  iteration_restart: False
  lr_scheduler_name: "WarmupCosineLR"
  warmup_iters: 10
