dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/3D/absorb/128x128x128'

model:
  architecture: 'DnCNN'
  DnCNN:
    do_3d: True
output_dir: 'results/3D/dncnn/absorb/128x128x128/'