dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/3D/homo/128x128x128'

model:
  architecture: 'DnCNN'
  checkpoint: "checkpoints/3D/blind-denoising/dncnn/version_2/checkpoints/epoch=1497-MSE=0.0073-SSIM=0.9620-PSNR=61.4440.ckpt"
  DnCNN:
    do_3d: True
output_dir: 'results/3D/dncnn/homo/128x128x128/'