dataset:
  paths:
    Simulation: "data/test/3D/colin27/"
    "Cascaded DnCNN + UNet": "results/3D/cascaded/colin27/"
    UNet: "results/3D/unet/colin27/"
    ResMCNet: "results/3D/resmcnet/colin27/"
    DnCNN: "results/3D/dncnn/colin27/"
    DRUNet: "results/3D/drunet/colin27/"
    "GPU ANLM": "results/3D/gpu_anlm/colin27/"
    BM4D: "results/3D/bm4d/colin27/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
output_path: "./analysis/3D/colin27"
