dataset:
  paths:
    Simulation: "data/test/3D/lens/"
    "Cascaded DnCNN + UNet": "results/3D/cascaded/lens/"
    UNet: "results/3D/unet/lens/"
    ResMCNet: "results/3D/resmcnet/lens/"
    DnCNN: "results/3D/dncnn/lens/"
    DRUNet: "results/3D/drunet/lens/"
    "GPU ANLM": "results/3D/gpu_anlm/lens/"
    BM4D: "results/3D/bm4d/lens/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
output_path: "./analysis/3D/lens"
