dataset:
  paths:
    Simulation: "data/test/3D/USC195/"
    "Cascaded DnCNN + UNet": "results/3D/cascaded/use195/"
    UNet: "results/3D/unet/use195/"
    ResMCNet: "results/3D/resmcnet/use195/"
    DnCNN: "results/3D/dncnn/use195/"
    DRUNet: "results/3D/drunet/usc195/"
    "GPU ANLM": "results/3D/gpu_anlm/use195/"
    BM4D: "results/3D/bm4d/use195/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
output_path: "./analysis/3D/use195"