dataset:
  paths:
    Simulation: "data/test/2D/absorb/100x100/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/absorb/100x100/"
    UNet: "results/2D/unet/absorb/100x100/"
    ResMCNet: "results/2D/resmcnet/absorb/100x100/"
    DnCNN: "results/2D/dncnn/absorb/100x100/"
    DRUNet: "results/2D/drunet/absorb/100x100/"
    NLM: "results/2D/nlm/absorb/100x100/"
    BM3D: "results/2D/bm4d/absorb/100x100/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
plot: ['Simulation', 'Cascaded DnCNN + UNet', 'BM3D']
cross_section:
  x: 50
figures:
  fig_type: "save"
output_path: "./analysis/2D/absorb-100x100"
zero_infs: False
zero_nans: False

