dataset:
  paths:
    Simulation: "data/test/2D/absorb/64x64/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/absorb/64x64/"
    UNet: "results/2D/unet/absorb/64x64/"
    ResMCNet: "results/2D/resmcnet/absorb/64x64/"
    DnCNN: "results/2D/dncnn/absorb/64x64/"
    DRUNet: "results/2D/drunet/absorb/64x64/"
    NLM: "results/2D/nlm/absorb/64x64/"
    BM3D: "results/2D/bm4d/absorb/64x64/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
plot: ['Simulation', 'Cascaded DnCNN + UNet', 'DRUNet', 'BM3D']
cross_section:
  x: 32
figures:
  fig_type: "save"
output_path: "./analysis/2D/absorb-64x64"
zero_infs: True
zero_nans: True

