dataset:
  paths:
    Simulation: "data/test/2D/homo/64x64/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/homo/64x64/"
    UNet: "results/2D/unet/homo/64x64/"
    ResMCNet: "results/2D/resmcnet/homo/64x64/"
    DnCNN: "results/2D/dncnn/homo/64x64/"
    DRUNet: "results/2D/drunet/homo/64x64/"
    NLM: "results/2D/nlm/homo/64x64/"
    BM3D: "results/2D/bm4d/homo/64x64/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
plot: ['Simulation', 'Cascaded DnCNN + UNet', 'BM3D']
cross_section:
  x: 32
figures:
  fig_type: "save"
output_path: "./analysis/2D/homo-64x64"
zero_infs: False
zero_nans: False

