model:
  architecture: 'DnCNN'
  checkpoint: "checkpoints/3D/blind-denoising/dncnn/version_2/checkpoints/epoch=1497-MSE=0.0073-SSIM=0.9620-PSNR=61.4440.ckpt"
  DnCNN:
    do_3d: True
input_dims: (1, 1, 181, 217, 181)
num_iterations: 100
unpaded_volume_slice: "slice(None), slice(None), slice(0, 181), slice(0, 217), slice(0, 181)"