dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8', 'x1e9']
  output_label: 'x1e9'
  test_path: 'data/test/2D/homo/128x128'

model:
  architecture: 'ResidualDnCNN'
  checkpoint: "checkpoints/2D/blind-denoising/resmcnet/version_0/checkpoints/epoch=1498-MSE=0.2071-SSIM=0.9113-PSNR=51.3357.ckpt"
  ResidualDnCNN:
    do_3d: False
output_dir: 'results/2D/resmcnet/homo/128x128/'