dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/2D/refractive/64x64'

model:
  architecture: 'ResidualDnCNN'
  checkpoint:
  ResidualDnCNN:
    do_3d: False
output_dir: 'results/2D/resmcnet/refractive/64x64/'