pytorch_lightning:
  checkpoint_dir: './checkpoints/2D/blind-denoising/'
  experiment_name: 'drunet'
  num_gpus: 8
  num_nodes: 1
  accelerator: 'ddp'
  visualize: False
  seed: 1

dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  valid_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  train_path: 'data/train/2D/64x64'
  valid_path: 'data/validation/2D/128x128'
model:
  architecture: 'DRUNet'
  DRUNet:
    do_3d: False
    num_res_blocks: 4
loss:
  loss_option: ['MSE']

solver:
  optimizer: 'AdamW'
  batch_size: 32
  base_lr: 5e-3
  total_iterations: 1500
  iteration_restart: False
  lr_scheduler_name: "WarmupCosineLR"
  warmup_iters: 10
