dataset:
  paths:
#    simulation: "data/test/3D/colin27"
#    cascaded_dncnn_mae+ssim: "results/3D/colin27/cascaded/"
#    unet: 'results/3D/colin27/unet/'
#    gpu_anlm: 'results/anlm/3D/colin27/'
    simulation: "data/test/3D/refractive/64x64x64"
    cascaded: "results/refractive-64x64x64-cascaded/"
    unet: "results/3D/refractive/64x64x64/unet/"
#    gpu_anlm: "results/3D/refractive/64x64x64/cascaded/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
cross_section:
  x: 32
  y: 32
figures:
  fig_type: "save"
  output_path: "."
zero_infs: False
zero_nans: False
