dataset:
  paths:
    Simulation: "data/test/3D/homo/100x100x100/"
    "Cascaded UNet + DnCNN": "results/3D/cascaded/homo/100x100x100/"
#    unet: "results/3D/unet/homo/64x64x64/"
#    resmcnet: "results/3D/resmcnet/homo/64x64x64/"
#    dncnn: "results/3D/dncnn/homo/64x64x64/"
#    DRUNet: "results/3D/drunet/homo/64x64x64/"
    "GPU ANLM": "results/3D/gpu_anlm/homo/100x100x100/"
#    nlm: "results/3D/nlm/homo/64x64x64/"
#    bm4d: "results/3D/bm4d/homo/64x64x64/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
cross_section:
  x: 50
  y: 50
figures:
  fig_type: "save"
output_path: "./analysis/3D/homo-100x100x100"
zero_infs: False
zero_nans: False

