dataset:
  paths:
    simulation: "data/test/3D/homo/64x64x64/"
    cascaded: "results/3D/cascaded/homo/64x64x64/"
    unet: "results/3D/unet/homo/64x64x64/"
    resmcnet: "results/3D/resmcnet/homo/64x64x64/"
    dncnn: "results/3D/dncnn/homo/64x64x64/"
    drunet: "results/3D/drunet/homo/64x64x64/"
    gpu_anlm: "results/3D/gpu_anlm/homo/64x64x64/"
    nlm: "results/3D/nlm/homo/64x64x64/"
    bm4d: "results/3D/bm4d/homo/64x64x64/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
cross_section:
  x: 32
  y: 32
figures:
  fig_type: "save"
output_path: "./analysis/homo-64x64x64"
zero_infs: False
zero_nans: False

