dataset:
  paths:
    Simulation: "data/test/3D/refractive/100x100x100/"
    "Cascaded DnCNN + UNet": "results/3D/cascaded/refractive/100x100x100/"
    UNet: "results/3D/unet/homo/100x100x100/"
    ResMCNet: "results/3D/resmcnet/homo/100x100x100/"
    DnCNN: "results/3D/dncnn/homo/100x100x100/"
    DRUNet: "results/3D/drunet/homo/100x100x100/"
    "GPU ANLM": "results/3D/gpu_anlm/homo/100x100x100/"
    BM4D: "results/3D/bm4d/homo/100x100x100/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
plot: ['Simulation', 'Cascaded DnCNN + UNet', 'DRUNet', 'GPU ANLM']
cross_section:
  x: 50
  y: 50
figures:
  fig_type: "save"
output_path: "./analysis/3D/refractive-100x100x100"
zero_infs: False
zero_nans: False

