checkpoint_dir: './results/model: cascaded/'

dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8', 'x1e9']
  output_label: 'x1e9'
  train_path: '../../Dataset/MCX/rand2d/train'
  valid_path: '../../Dataset/MCX/rand2d/validation'
  test_path: '../../Dataset/MCX/rand2d/test/absorb-2d-new'

model:
  architecture: 'Cascaded'
  Cascaded:
    num_dncnn: 3
loss:
  loss_option: ['MSE',]
solver:
  batch_size: 8
inference:
  output_dir: './results/absorb-2d/'
  checkpoint_dir: './final_results/cascaded_dncnn/cascaded_dncnn_final.pt'
  do_2d: False
visualize: False