checkpoint_dir: './results/model: Cascaded; Loss: L2; Attempt: 1; Label: All labels'

dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  valid_path: '../../Dataset/MCX/3D/test/absorb/'

model:
  architecture: 'Cascaded'
  Cascaded:
    num_dncnn: 1
solver:
  batch_size: 8
inference:
  output_dir: './results/absorb/cascaded/'
  checkpoint_dir: './checkpoint/best_cascaded/model_chkpt.pt'
  do_2d: True
visualize: False