model:
  architecture: 'DRUNet'
  checkpoint: "checkpoints/3D/blind-denoising/drunet/version_1/checkpoints/epoch=1499-MSE=0.0027-SSIM=0.9851-PSNR=63.9906.ckpt"
  DRUNet:
    do_3d: True
input_dims: (1, 1, 192, 496, 104)
num_iterations: 100
unpaded_volume_slice: "slice(None), slice(None), slice(0, 190), slice(0, 496), slice(0, 104)"