dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/3D/absorb/64x64x64'

model:
  architecture: 'Cascaded'
  checkpoint: "checkpoints/3D/blind-denoising/cascaded/version_2/checkpoints/epoch=1494-MSE=0.0043-SSIM=0.9731-PSNR=62.2551.ckpt"
  Cascaded:
    do_3d: True
    num_dncnn_layers: 17
    unet_activation_fn: 'F.relu'
output_dir: 'results/3D/cascaded/absorb/64x64x64/'