dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/3D/digimouse'

model:
  architecture: 'Cascaded'
  checkpoint:
  Cascaded:
    do_3d: True
    num_dncnn_layers: 17
    unet_activation_fn: 'F.relu'
output_dir: 'results/3D/cascaded/digimouse/'