checkpoint_dir: './checkpoint/Cascaded 3D/'

dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  train_path: '../../Dataset/MCX/3D/train/'
  valid_path: '../../Dataset/MCX/3D/valid'

model:
  architecture: 'Cascaded'
  Cascaded:
    num_dncnn: 1
solver:
  batch_size: 8
inference:
  output_dir: './results/absorb/cascaded/'
  checkpoint_dir: './checkpoint/best_cascaded/model_chkpt.pt'
  do_2d: True
visualize: False