dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8', 'x1e9']
  output_label: 'x1e9'
  test_path: 'data/test/2D/USE195'
  padding: 4

model:
  architecture: 'DnCNN'
  checkpoint: "checkpoints/2D/blind-denoising/dncnn/version_0/checkpoints/epoch=1491-MSE=0.1963-SSIM=0.9113-PSNR=50.9365.ckpt"
  DnCNN:
    do_3d: False
output_dir: 'results/2D/dncnn/use195/'