model:
  architecture: 'ResidualDnCNN'
  checkpoint: "checkpoints/3D/blind-denoising/resmcnet/version_2/checkpoints/epoch=1499-MSE=0.0036-SSIM=0.9742-PSNR=63.0294.ckpt"
  ResidualDnCNN:
    do_3d: True
input_dims: (1, 1, 100, 100, 100)
num_iterations: 100
unpaded_volume_slice: "slice(None), slice(None), slice(0, 100), slice(0, 100), slice(0, 100)"