dataset:
  paths:
    Simulation: "data/test/2D/homo/128x128/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/homo/128x128/"
    UNet: "results/2D/unet/homo/128x128/"
    ResMCNet: "results/2D/resmcnet/homo/128x128/"
    DnCNN: "results/2D/dncnn/homo/128x128/"
    DRUNet: "results/2D/drunet/homo/128x128/"
    NLM: "results/2D/nlm/homo/128x128/"
    BM3D: "results/2D/bm4d/homo/128x128/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
output_path: "./analysis/2D/homo-128x128"
