dataset:
  paths:
    Simulation: "data/test/2D/refractive/64x64/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/refractive/64x64/"
    UNet: "results/2D/unet/refractive/64x64/"
    ResMCNet: "results/2D/resmcnet/refractive/64x64/"
    DnCNN: "results/2D/dncnn/refractive/64x64/"
    DRUNet: "results/2D/drunet/refractive/64x64/"
    NLM: "results/2D/nlm/refractive/64x64/"
    BM3D: "results/2D/bm4d/refractive/64x64/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
output_path: "./analysis/2D/refractive-64x64"
