dataset:
  paths:
    Simulation: "data/test/3D/homo/100x100x100/"
    "Cascaded DnCNN + UNet": "results/3D/cascaded/homo/100x100x100/"
    "GPU ANLM": "results/3D/gpu_anlm/homo/100x100x100/"
  labels: ["x1e5", "x1e6", "x1e7", "x1e8", "x1e9"]
cross_section:
  x: 50
  y: 50
figures:
  legend: True
  fig_type: "save"
output_path: "./analysis/3D/homo-100x100x100"
zero_infs: False
zero_nans: False

