dataset:
  paths:
    Simulation: "data/test/3D/USC195/"
    "Cascaded DnCNN + UNet": "results/3D/cascaded/use195/"
    "GPU ANLM": "results/3D/gpu_anlm/use195/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8", "x1e9"]
cross_section:
  x: 83
  y: 50
figures:
  legend: True
  fig_type: "save"
output_path: "./analysis/3D/use195"
zero_infs: False
zero_nans: False

