checkpoint_dir: './results/model: Cascaded; Loss: L2; Attempt: 1; Label: All labels'

dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7']
  output_label: 'x1e8'
  valid_path: './data/test_snr/square/'

model:
  architecture: 'Cascaded'
  #starting_checkpoint: './checkpoint/dncnn-l2-loss-chkpt/model_chkpt.pt'
solver:
  batch_size: 8
inference:
  output_dir: './results/square/'