checkpoint_dir: './results/model: Cascaded; Loss: L2; Attempt: 1; Label: All labels'

dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']

model:
  architecture: 'Cascaded'
  #starting_checkpoint: './checkpoint/dncnn-l2-loss-chkpt/model_chkpt.pt'
solver:
  batch_size: 8