dataset:
  paths:
    Simulation: "data/test/2D/absorb/100x100/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/absorb/100x100/"
    BM3D: "results/2D/bm4d/absorb/100x100/"
  labels: ["x1e5", "x1e6", "x1e7", "x1e8", "x1e9"]
cross_section:
  x: 50
figures:
  legend: True
  fig_type: "save"
output_path: "./analysis/2D/absorb-100x100"
zero_infs: False
zero_nans: False

