dataset:
  paths:
    Simulation: "data/test/2D/homo/100x100/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/homo/100x100/"
    BM3D: "results/2D/bm4d/homo/100x100/"
  labels: ["x1e5", "x1e6", "x1e7", "x1e8", "x1e9"]
cross_section:
  x: 50
figures:
  legend: true
  fig_type: "save"
output_path: "./analysis/2D/homo-100x100"
zero_infs: False
zero_nans: False