dataset:
  paths:
    Simulation: "data/test/2D/refractive/128x128/"
    "Cascaded DnCNN + UNet": "results/2D/cascaded/refractive/128x128/"
    BM3D: "results/2D/bm4d/refractive/128x128/"
  labels: ["x1e5", "x1e6", "x1e7", "x1e8", "x1e9"]
cross_section:
  x: 64
figures:
  legend: True
  fig_type: "save"
output_path: "./analysis/2D/refractive-128x128"
zero_infs: False
zero_nans: False