dataset:
  paths:
    simulation:
      'Absorbing Square': "data/test/2D/absorb/100x100/"
      'Refractive Square': "data/test/2D/refractive/100x100/"
      'Homogenous': "data/test/2D/homo/100x100/"
    NLM:
      'Absorbing Square': "results/2D/nlm/absorb/100x100/"
      'Refractive Square': "results/2D/nlm/refractive/100x100/"
      'Homogenous': "results/2D/nlm/homo/100x100/"
    BM3D:
      'Absorbing Square': "results/2D/bm4d/absorb/100x100/"
      'Refractive Square': "results/2D/bm4d/refractive/100x100/"
      'Homogenous': "results/2D/bm4d/homo/100x100/"
    DnCNN:
      'Absorbing Square': "results/2D/dncnn/absorb/100x100/"
      'Refractive Square': "results/2D/dncnn/refractive/100x100/"
      'Homogenous': "results/2D/dncnn/homo/100x100/"
    ResMCNet:
      'Absorbing Square': "results/2D/resmcnet/absorb/100x100/"
      'Refractive Square': "results/2D/resmcnet/refractive/100x100/"
      'Homogenous': "results/2D/resmcnet/homo/100x100/"
    Cascaded:
      'Absorbing Square': "results/2D/cascaded/absorb/100x100/"
      'Refractive Square': "results/2D/cascaded/refractive/100x100/"
      'Homogenous': "results/2D/cascaded/homo/100x100/"
    UNet:
      'Absorbing Square': "results/2D/unet/absorb/100x100/"
      'Refractive Square': "results/2D/unet/refractive/100x100/"
      'Homogenous': "results/2D/unet/homo/100x100/"
    DRUNet:
      'Absorbing Square': "results/2D/drunet/absorb/100x100/"
      'Refractive Square': "results/2D/drunet/refractive/100x100/"
      'Homogenous': "results/2D/drunet/homo/100x100/"

  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
dataset_name_on_rows: True
output_path: "./visualization/2D/square-100x100"
font_size: 35
fig_size: (80, 20)

