dataset:
  paths:
    simulation: "data/test/2D/USE195/"
    BM3D: "results/2D/bm4d/use195/"
    DnCNN: "results/2D/dncnn/use195/"
    ResMCNet: "results/2D/resmcnet/use195/"
    Cascaded: "results/2D/cascaded/use195/"
    UNet: "results/2D/unet/use195/"
    DRUNet: "results/2D/drunet/use195/"

  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
  crop: "(83, slice(0, 180), slice(130, None))"
  rotate:
    do: True
    k: 1
contour:
  path: "matlab/volume/fullhead_atlas.mat"
  name: "USC_atlas"
dataset_name_on_rows: True
output_dir: "./visualization/2D/usc-195/"
font_size: 50
fig_size: (100, 20)

