dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/3D/refractive/64x64x64'

model:
  architecture: 'DRUNet'
  checkpoint:
  DRUNet:
    do_3d: True
output_dir: 'results/3D/drunet/refractive/64x64x64/'