dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8', 'x1e9']
  output_label: 'x1e9'
  test_path: 'data/test/2D/absorb/128x128'

model:
  architecture: 'UNet'
  checkpoint: "checkpoints/2D/blind-denoising/unet/version_0/checkpoints/epoch=1499-MSE=0.1426-SSIM=0.8984-PSNR=51.5891.ckpt"
  UNet:
    activation_fn: 'F.relu'
    do_3d: False
output_dir: 'results/2D/unet/absorb/128x128/'