dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/validation/2D/128x128'

model:
  architecture: 'Cascaded'
  checkpoint: "checkpoints/2D/blind-denoising/cascaded/version_0/checkpoints/epoch=1498-MSE=0.1569-SSIM=0.9036-PSNR=51.2722.ckpt"
  Cascaded:
    do_3d: False
    num_dncnn_layers: 17
    unet_activation_fn: 'F.relu'
output_dir: 'results/2D/cascaded/validation/128x128/'