dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/validation/2D/64x64'

model:
  architecture: 'Cascaded'
  checkpoint: 'checkpoints/2D/blind-denoising/cascaded-old/version_6/checkpoints/epoch=0332-MSE=0.1637-SSIM=0.8390-PSNR=51.6326.ckpt'
  Cascaded:
    do_3d: False
    num_dncnn_layers: 17
    unet_activation_fn: 'F.relu'
output_dir: 'results/2D/cascaded/validation/64x64/'