dataset:
  paths:
    simulation: "data/test/3D/homo/100x100x100/"
    BM4D: "results/3D/bm4d/homo/100x100x100/"
    'GPU ANLM': "results/3D/gpu_anlm/homo/100x100x100/"
    DnCNN: "results/3D/dncnn/homo/100x100x100/"
    ResMCNet: "results/3D/resmcnet/homo/100x100x100/"
    Cascaded: "results/3D/cascaded/homo/100x100x100/"
    UNet: "results/3D/unet/homo/100x100x100/"
    DRUNet: "results/3D/drunet/homo/100x100x100/"

  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8", "x1e9"]
  output_label: "x1e9"
  crop: "(50, slice(0, None), slice(0, None))"
  rotate:
    do: False
    k: 0
contour: None
dataset_name_on_rows: True
output_dir: "./visualization/3D/homo-100x100x100/"
font_size: 70
fig_size: (80, 37)

