dataset:
  paths:
    simulation:
      'Absorbing Square': "data/test/3D/absorb/128x128x128/"
      'Refractive Square': "data/test/3D/refractive/128x128x128/"
      'Homogenous': "data/test/3D/homo/128x128x128/"
    BM4D:
      'Absorbing Square': "results/3D/bm4d/absorb/128x128x128/"
      'Refractive Square': "results/3D/bm4d/refractive/128x128x128/"
      'Homogenous': "results/3D/bm4d/homo/128x128x128/"
    DnCNN:
      'Absorbing Square': "results/3D/dncnn/absorb/128x128x128/"
      'Refractive Square': "results/3D/dncnn/refractive/128x128x128/"
      'Homogenous': "results/3D/dncnn/homo/128x128x128/"
    ResMCNet:
      'Absorbing Square': "results/3D/resmcnet/absorb/128x128x128/"
      'Refractive Square': "results/3D/resmcnet/refractive/128x128x128/"
      'Homogenous': "results/3D/resmcnet/homo/128x128x128/"
    Cascaded:
      'Absorbing Square': "results/3D/cascaded/absorb/128x128x128/"
      'Refractive Square': "results/3D/cascaded/refractive/128x128x128/"
      'Homogenous': "results/3D/cascaded/homo/128x128x128/"
    UNet:
      'Absorbing Square': "results/3D/unet/absorb/128x128x128/"
      'Refractive Square': "results/3D/unet/refractive/128x128x128/"
      'Homogenous': "results/3D/unet/homo/128x128x128/"
    DRUNet:
      'Absorbing Square': "results/3D/drunet/absorb/128x128x128/"
      'Refractive Square': "results/3D/drunet/refractive/128x128x128/"
      'Homogenous': "results/3D/drunet/homo/128x128x128/"
  input_labels: ["x1e5", "x1e6", "x1e7", "x1e8"]
  output_label: "x1e9"
dataset_name_on_rows: True
output_path: "./visualization/3D/square-128x128x128"
font_size: 45
fig_size: (100, 30)

