dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/2D/colin27'
  padding: 8

model:
  architecture: 'DRUNet'
  checkpoint: "checkpoints/2D/blind-denoising/drunet/version_0/checkpoints/epoch=1499-MSE=0.1888-SSIM=0.9267-PSNR=52.4070.ckpt"
  DRUNet:
    do_3d: False
    num_res_blocks: 4
output_dir: 'results/2D/drunet/colin27'