dataset:
  input_labels: ['x1e5', 'x1e6', 'x1e7', 'x1e8']
  output_label: 'x1e9'
  test_path: 'data/test/2D/homo/64x64'

model:
  architecture: 'DRUNet'
  checkpoint:
  DRUNet:
    do_3d: False
    num_res_blocks: 4
output_dir: 'results/2D/drunet/homo/64x64/'